name: Build & Push Docker Image to ECR

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-test:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    uses: ./.github/workflows/unit-test.yaml


