# .github/workflows/pipeline.yaml
name: Build & Push Docker Image to ECR

on:
  # push:
  #   branches: ["dev", "main"]
  pull_request:
    branches: ["main"]  # Ensure tests run on PRs into 'main'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml


