name: Build & Push Docker Image to ECR

on:
  push:
    branches: ["dev","main"]
  pull_request:
    branches: ["dev","main"]
  workflow_dispatch:  

jobs:
  unit-test :
    # needs: sast
    if: github.ref == 'refs/heads/main' 
    uses: ./.github/workflows/unit-test.yaml